### ISSUE TITLE
Refactor code to make use of preprocess_priviliges helper function throughout code base

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-lookup-server#10]
@jotelha - is my understanding correct that we could make more use of the helper function you implemented?

**Comment by jotelha** [comment]
I am not sure whether there would be much more refactoring necessary in the core server, apart from the already introduced line at https://github.com/jic-dtool/dtool-lookup-server/blob/41f800ad48bd184448d5d52328c125eb7bfa828c/dtool_lookup_server/utils.py#L310

The main reason I suggested introducing this tiny helper was that I wanted to build mongo queries in my plugins that adhere to user permissions coherent with the core server's mechanism, i.e. at

https://github.com/IMTEK-Simulation/dtool-lookup-server-dependency-graph-plugin/blob/b710300f12594824f98689e0739e9829eb15f596/dtool_lookup_server_dependency_graph_plugin/utils.py#L201-L209

https://github.com/IMTEK-Simulation/dtool-lookup-server-direct-mongo-plugin/blob/643df193405bc86f56e0b66ac75343148071ee86/dtool_lookup_server_direct_mongo_plugin/utils.py#L84

and

https://github.com/IMTEK-Simulation/dtool-lookup-server-direct-mongo-plugin/blob/643df193405bc86f56e0b66ac75343148071ee86/dtool_lookup_server_direct_mongo_plugin/utils.py#L125

**Comment by tjelvar-olsson** [comment]
It looks like there this is complete. However, since you are using this function in your code I think we should make the function public. I would also like to make the function name more explicit.

@jotelha how about renaming the function from ``_preprocess_priviliges`` to ``preprocess_query_base_uris``?

**Comment by jotelha** [comment]
Sure.

**Comment by tjelvar-olsson** [comment]
I have implemented this in a backwards compatible way (i.e. the _preprocess_priviliges function is still in the code). I also added tests to the new ``preprocess_query_base_uris`` helper funciton. See eff0770
