### ISSUE TITLE
Add ability to expose config values from plugins in /config route

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-lookup-server#11]
@jotelha - I believe this is a missing feature, is that correct?

**Comment by jotelha** [comment]
True, so far I have just implemented plugin-wise configurations in an analogous structure to the main server configuration, i.e. 

https://github.com/IMTEK-Simulation/dtool-lookup-server-direct-mongo-plugin/blob/master/dtool_lookup_server_direct_mongo_plugin/config.py

and

https://github.com/IMTEK-Simulation/dtool-lookup-server-dependency-graph-plugin/blob/master/dtool_lookup_server_dependency_graph_plugin/config.py

which are then accessible via independent routes, i.e. `/mongo/config` or `/graph/config`, as implemented within the plugin.

What do you think of allowing (not forcing) a plugin to register a config serialization function like

https://github.com/IMTEK-Simulation/dtool-lookup-server-dependency-graph-plugin/blob/b710300f12594824f98689e0739e9829eb15f596/dtool_lookup_server_dependency_graph_plugin/config.py#L54-L62

with the core server - in a similar manner as registering blueprints via entrypoints - for allowing their config key-value pairs to be embedded in the core /config route response?

**Comment by tjelvar-olsson** [comment]
@jotelha I belive this is is implemented with https://github.com/jic-dtool/dtool-lookup-server/pull/12. Is that correct?

**Comment by jotelha** [comment]
Yes. Pleas close the issue.
