### ISSUE TITLE
Automized tests

### ISSUE THREAD

**Issue by jotelha** [jic-dtool/dtool-lookup-server#14]
@tjelvar-olsson what do you think about putting some github testing workflow on pushes and pull requests like this https://github.com/IMTEK-Simulation/dtool-lookup-server-plugin-scaffolding/blob/master/.github/workflows/test.yml into the dtool-lookup-server core repository as well?

**Comment by tjelvar-olsson** [comment]
This repo did have continues integration (CI) tests setup on Travis. However, that seems to have stopped working for some reason. It seems like Travis has moved from travis-ci.org to travis-ci.com and I need to register for the latter.

What CI system does your code use?

**Comment by jotelha** [comment]
It just uses github's own "actions" interface, see https://github.com/IMTEK-Simulation/dtool-lookup-server-plugin-scaffolding/actions

If you can get Travis CI working again without effort, then maybe better stick with that.

I haven't used CI a lot, but from what I understand is that those github actions do not exist since that long, Lars originally asked me to add some automized PyPI publication workflow https://github.com/IMTEK-Simulation/dtool-lookup-server-plugin-scaffolding/blob/master/.github/workflows/publish.yml, and after doing this, running tests via that framework as well seemed a logical and simple next step.

**Comment by tjelvar-olsson** [comment]
I seem to have managed to get travis-ci.org to work again. Or perhaps it was working all the time. However, I'm surprised I have not got emails about failing builds. Either way, below is the link to the CI test page.

https://travis-ci.org/github/jic-dtool/dtool-lookup-server

I'm closing this issue but will keep an eye on the CI setup to make sure it works as expected.
