### ISSUE TITLE
Add support for pagination

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-lookup-server#23]
In particular to the routes for listing and searching for datasets

**Comment by tjelvar-olsson** [comment]
This should be done in a backwards compatible way

**Comment by jotelha** [comment]
This has been solved with the openapi branch merge https://github.com/jic-dtool/dtool-lookup-server/commit/f47c8ab7ad312b97b1f57c7d3b22027e6655db26, in a somewhat backwards-compatible way:

* Any pagination-decorated routes need to be called with parameters now, i.e. `https://demo.dtool.dev/lookup/dataset/search?page=1&page_size=10`.
*  Before, the route `https://demo.dtool.dev/lookup/dataset/search` (without parameters) would yield the whole list of datasets.
* Now, the same route `https://demo.dtool.dev/lookup/dataset/search` still works, but would just yield a limited list of datasets according to default pagination parameters. The actual information of what you get is found within the response header `X-Pagination: {"total": 124, "total_pages": 13, "first_page": 1, "last_page": 13, "page": 1, "next_page": 2}`.

I think, that's fine, there are a few likely non-backwards compatible changes in the current modular server refactor anyway.
