### ISSUE TITLE
Architectural restructuring: SearchABC and MetadataABC

### ISSUE THREAD

**Issue by jotelha** [jic-dtool/dtool-lookup-server#26]
Looking at https://github.com/jic-dtool/dtool-lookup-server/blob/architectural-restructuring/experiments/SPEC.rst#metadata, what's your motivation in introducing an additional MetadataABC? I understand that currently administrative metadata is stored in an SQL database and descriptive metadata (i.e. the README.yml) in the MongoDB. The SQL database is basically used for managing and querying privileges, while searches happen on the MongoDB. Your thought here is to completely distinguish the storage of searchable metadata from the storage of metadata retrievable from the lookup server via API?

**Comment by tjelvar-olsson** [comment]
Re-read what I wrote I think it might be worth merging search and metadata.

However, I think the point of separating them was that their functions are
quite different. One is to enable full text search, and another is to
retrieve documents. As such one child imagine wanting to be able to swap
out the components separately.

Does that make sense?

**Comment by jotelha** [comment]
We have them decoupled now with the SearchABC and RetrieveABC and the respective search and retrieve plugins. Will close this issue.
