### ISSUE TITLE
'/dataset/list' vs '/dataset/search'

### ISSUE THREAD

**Issue by pastewka** [jic-dtool/dtool-lookup-server#3]
'/dataset/list' returns time stamps for dates but '/dataset/search' returns strings.

Is this intentional? If not, my suggestion is to switch to timestamps throughout. I'd be happy to contribute this fix, would this break anything on the WebApp side?

Any comments @tjelvar-olsson

**Comment by tjelvar-olsson** [comment]
@pastewka I'll start working on this now

**Comment by pastewka** [comment]
Okay, thank you!

**Comment by tjelvar-olsson** [comment]
Fixed in 12bc0c2

Closing
