### ISSUE TITLE
documentation errors

### ISSUE THREAD

**Issue by robbytobby** [jic-dtool/dtool-lookup-server#45]
mongodb server needs to be installed and running prior to 
```flask db init```
or you'll get a connection error
```
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 642ad34229fe0e914afe6ae3, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
```
and you need to install python3-mysqldb before being able to migrate (and of course use) the mysql database.

and one more:
the default keypair generated by ssh-keygen do not work as jwt_keys. Token creation results in
```
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=75497580, lib=9, reason=108, reason_text=no start line)>])

```
you need to create the keys in PEM format 
```ssh-keygen -m PEM```
or
```
openssl genrsa -out jwt_key 2048
openssl rsa -in jwt_key  -pubout -outform PEM -out jwt_key.pub
```

**Comment by jotelha** [comment]
Hi @robbytobby , thanks for reporting. I think `python3-mysqldb` is not part of the strict requirements as one can opt to use other SQL databases as well, and will then need to install other Python adapters, e.g. PostgreSQL + psycopg2.

Will come back to the other bits later.

**Comment by jotelha** [comment]
I added some notes with respect to these issues to the `README,md`,

https://github.com/jotelha/dtool-lookup-server/commit/07ea68c5a3aa19b072ed000329998e26bd33412a
https://github.com/jotelha/dtool-lookup-server/commit/23a936913879382317e14e224dba30041ad888f3

So far, these are not in the main branch here, but on a development branch on my own fork.

**Comment by jotelha** [comment]
These documentation modifications are in the master already, will close this issue as resolved.
