### ISSUE TITLE
Add authentication to /config route

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-lookup-server#9]
Add test and implement authentication of /config route

@jotelha - is my understanding correct that this is missing?

**Comment by jotelha** [comment]
Yes, I did just put the username retrieval https://github.com/jic-dtool/dtool-lookup-server/blob/41f800ad48bd184448d5d52328c125eb7bfa828c/dtool_lookup_server/config_routes.py#L23 into the route as a stub, there is no permission checking implemented yet.

**Comment by tjelvar-olsson** [comment]
Fixed in 9fe5e15
